// Code generated by ws-codegen; DO NOT EDIT.

package realtime

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"math/rand"
	"sync"
	"time"

	"nhooyr.io/websocket"
)

const (
	defaultURL               = "wss://api.newsrank.ai/ws"
	defaultHeartbeatInterval = 30 * time.Second
	defaultMaxReconnect      = 0 // unlimited
	maxBackoff               = 30 * time.Second
)

// Client is a WebSocket client for the NewsRank Realtime API.
type Client struct {
	apiKey string
	url    string

	autoReconnect        bool
	maxReconnectAttempts int
	heartbeatInterval    time.Duration

	conn      *websocket.Conn
	connected bool
	mu        sync.RWMutex

	// Last subscribe message for replay on reconnect.
	lastFilters *SubscribeFilters

	// Typed event handlers.
	onSubscribed func(ctx context.Context, e *SubscribedEvent)
	onItemNew func(ctx context.Context, e *ItemNewEvent)
	onItemEnriched func(ctx context.Context, e *ItemEnrichedEvent)
	onClustersRanked func(ctx context.Context, e *ClustersRankedEvent)
	onStoryDevelopment func(ctx context.Context, e *StoryDevelopmentEvent)
	onStoryPriorityChanged func(ctx context.Context, e *StoryPriorityChangedEvent)
	onClusterEvent func(ctx context.Context, e *ClusterEventEvent)
	onTickerNews func(ctx context.Context, e *TickerNewsEvent)
	onError func(ctx context.Context, e *ErrorEvent)
}

// NewClient creates a new Realtime API client.
func NewClient(apiKey string, opts ...Option) *Client {
	c := &Client{
		apiKey:               apiKey,
		url:                  defaultURL,
		autoReconnect:        true,
		maxReconnectAttempts: defaultMaxReconnect,
		heartbeatInterval:    defaultHeartbeatInterval,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

// Dial connects to the WebSocket server.
func (c *Client) Dial(ctx context.Context) error {
	c.mu.Lock()
	if c.connected {
		c.mu.Unlock()
		return ErrAlreadyConnected
	}
	c.mu.Unlock()

	return c.dial(ctx)
}

func (c *Client) dial(ctx context.Context) error {
	url := c.url + "?token=" + c.apiKey
	conn, _, err := websocket.Dial(ctx, url, nil)
	if err != nil {
		return &RealtimeError{Message: "dial failed", Err: err}
	}

	c.mu.Lock()
	c.conn = conn
	c.connected = true
	c.mu.Unlock()

	return nil
}

// Close gracefully closes the WebSocket connection.
func (c *Client) Close() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	if !c.connected || c.conn == nil {
		return ErrNotConnected
	}

	c.connected = false
	err := c.conn.Close(websocket.StatusNormalClosure, "bye")
	c.conn = nil
	return err
}

// Connected returns whether the client is currently connected.
func (c *Client) Connected() bool {
	c.mu.RLock()
	defer c.mu.RUnlock()
	return c.connected
}

// Subscribe sends a subscribe message with optional filters.
func (c *Client) Subscribe(ctx context.Context, filters *SubscribeFilters) error {
	c.mu.RLock()
	conn := c.conn
	connected := c.connected
	c.mu.RUnlock()

	if !connected || conn == nil {
		return ErrNotConnected
	}

	// Store filters for replay on reconnect.
	c.mu.Lock()
	c.lastFilters = filters
	c.mu.Unlock()

	msg := struct {
		Type    string           `json:"type"`
		Filters *SubscribeFilters `json:"filters,omitempty"`
	}{
		Type:    EventSubscribe,
		Filters: filters,
	}

	data, err := json.Marshal(msg)
	if err != nil {
		return fmt.Errorf("realtime: marshal subscribe: %w", err)
	}

	return conn.Write(ctx, websocket.MessageText, data)
}

// Listen blocks, reading messages from the server and dispatching them to
// registered handlers. It returns when the context is cancelled or an
// unrecoverable error occurs. If auto-reconnect is enabled, transient
// connection failures trigger reconnection with exponential backoff.
func (c *Client) Listen(ctx context.Context) error {
	for {
		err := c.listenLoop(ctx)
		if ctx.Err() != nil {
			return ctx.Err()
		}
		if !c.autoReconnect {
			return err
		}
		if reconnErr := c.reconnect(ctx); reconnErr != nil {
			return reconnErr
		}
	}
}

func (c *Client) listenLoop(ctx context.Context) error {
	// Start heartbeat goroutine.
	heartCtx, heartCancel := context.WithCancel(ctx)
	defer heartCancel()
	go c.heartbeat(heartCtx)

	for {
		c.mu.RLock()
		conn := c.conn
		c.mu.RUnlock()
		if conn == nil {
			return ErrNotConnected
		}

		_, data, err := conn.Read(ctx)
		if err != nil {
			c.mu.Lock()
			c.connected = false
			c.mu.Unlock()
			return &RealtimeError{Message: "read failed", Err: err}
		}

		if err := c.dispatch(ctx, data); err != nil {
			// Dispatch errors are non-fatal; continue reading.
			continue
		}
	}
}

func (c *Client) dispatch(ctx context.Context, data []byte) error {
	var raw rawEvent
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("realtime: unmarshal type: %w", err)
	}

	switch raw.Type {
	case EventSubscribed:
		c.mu.RLock()
		fn := c.onSubscribed
		c.mu.RUnlock()
		if fn != nil {
			var ev SubscribedEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal subscribed: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventItemNew:
		c.mu.RLock()
		fn := c.onItemNew
		c.mu.RUnlock()
		if fn != nil {
			var ev ItemNewEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal item.new: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventItemEnriched:
		c.mu.RLock()
		fn := c.onItemEnriched
		c.mu.RUnlock()
		if fn != nil {
			var ev ItemEnrichedEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal item.enriched: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventClustersRanked:
		c.mu.RLock()
		fn := c.onClustersRanked
		c.mu.RUnlock()
		if fn != nil {
			var ev ClustersRankedEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal clusters.ranked: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventStoryDevelopment:
		c.mu.RLock()
		fn := c.onStoryDevelopment
		c.mu.RUnlock()
		if fn != nil {
			var ev StoryDevelopmentEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal story.development: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventStoryPriorityChanged:
		c.mu.RLock()
		fn := c.onStoryPriorityChanged
		c.mu.RUnlock()
		if fn != nil {
			var ev StoryPriorityChangedEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal story.priority_changed: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventClusterEvent:
		c.mu.RLock()
		fn := c.onClusterEvent
		c.mu.RUnlock()
		if fn != nil {
			var ev ClusterEventEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal cluster.event: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventTickerNews:
		c.mu.RLock()
		fn := c.onTickerNews
		c.mu.RUnlock()
		if fn != nil {
			var ev TickerNewsEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal ticker.news: %w", err)
			}
			fn(ctx, &ev)
		}
	case EventError:
		c.mu.RLock()
		fn := c.onError
		c.mu.RUnlock()
		if fn != nil {
			var ev ErrorEvent
			if err := json.Unmarshal(data, &ev); err != nil {
				return fmt.Errorf("realtime: unmarshal error: %w", err)
			}
			fn(ctx, &ev)
		}
	}

	return nil
}

func (c *Client) reconnect(ctx context.Context) error {
	var attempt int
	for {
		if c.maxReconnectAttempts > 0 && attempt >= c.maxReconnectAttempts {
			return &RealtimeError{Message: fmt.Sprintf("max reconnect attempts (%d) reached", c.maxReconnectAttempts)}
		}

		backoff := time.Duration(math.Min(
			float64(time.Second)*math.Pow(2, float64(attempt)),
			float64(maxBackoff),
		))
		// Add jitter: 0-25% of backoff.
		jitter := time.Duration(rand.Int63n(int64(backoff/4) + 1))
		backoff += jitter

		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(backoff):
		}

		if err := c.dial(ctx); err != nil {
			attempt++
			continue
		}

		// Replay last subscribe filters.
		c.mu.RLock()
		filters := c.lastFilters
		c.mu.RUnlock()
		if filters != nil {
			if err := c.Subscribe(ctx, filters); err != nil {
				attempt++
				continue
			}
		}

		return nil
	}
}

func (c *Client) heartbeat(ctx context.Context) {
	ticker := time.NewTicker(c.heartbeatInterval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			return
		case <-ticker.C:
			c.mu.RLock()
			conn := c.conn
			c.mu.RUnlock()
			if conn == nil {
				return
			}
			_ = conn.Ping(ctx)
		}
	}
}

// --- Typed event handler registration ---

// OnSubscribed registers a handler for subscribed events.
func (c *Client) OnSubscribed(fn func(ctx context.Context, e *SubscribedEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onSubscribed = fn
}

// OnItemNew registers a handler for item.new events.
func (c *Client) OnItemNew(fn func(ctx context.Context, e *ItemNewEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onItemNew = fn
}

// OnItemEnriched registers a handler for item.enriched events.
func (c *Client) OnItemEnriched(fn func(ctx context.Context, e *ItemEnrichedEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onItemEnriched = fn
}

// OnClustersRanked registers a handler for clusters.ranked events.
func (c *Client) OnClustersRanked(fn func(ctx context.Context, e *ClustersRankedEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onClustersRanked = fn
}

// OnStoryDevelopment registers a handler for story.development events.
func (c *Client) OnStoryDevelopment(fn func(ctx context.Context, e *StoryDevelopmentEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onStoryDevelopment = fn
}

// OnStoryPriorityChanged registers a handler for story.priority_changed events.
func (c *Client) OnStoryPriorityChanged(fn func(ctx context.Context, e *StoryPriorityChangedEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onStoryPriorityChanged = fn
}

// OnClusterEvent registers a handler for cluster.event events.
func (c *Client) OnClusterEvent(fn func(ctx context.Context, e *ClusterEventEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onClusterEvent = fn
}

// OnTickerNews registers a handler for ticker.news events.
func (c *Client) OnTickerNews(fn func(ctx context.Context, e *TickerNewsEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onTickerNews = fn
}

// OnError registers a handler for error events.
func (c *Client) OnError(fn func(ctx context.Context, e *ErrorEvent)) {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.onError = fn
}
