// Code generated by ws-codegen; DO NOT EDIT.

package realtime

import "errors"

var (
	ErrNotConnected     = errors.New("realtime: not connected")
	ErrAlreadyConnected = errors.New("realtime: already connected")
	ErrAuthFailed       = errors.New("realtime: authentication failed")
	ErrConnectionLimit  = errors.New("realtime: connection limit reached")
)

// RealtimeError wraps an underlying error with a human-readable message.
type RealtimeError struct {
	Message string
	Err     error
}

func (e *RealtimeError) Error() string {
	if e.Err != nil {
		return e.Message + ": " + e.Err.Error()
	}
	return e.Message
}

func (e *RealtimeError) Unwrap() error {
	return e.Err
}
