// Code generated by ws-codegen; DO NOT EDIT.

package realtime

import "time"

// Option configures the Client.
type Option func(*Client)

// WithURL overrides the default WebSocket URL.
func WithURL(url string) Option {
	return func(c *Client) {
		c.url = url
	}
}

// WithAutoReconnect enables or disables automatic reconnection.
func WithAutoReconnect(enabled bool) Option {
	return func(c *Client) {
		c.autoReconnect = enabled
	}
}

// WithMaxReconnectAttempts sets the maximum number of reconnect attempts.
// 0 means unlimited.
func WithMaxReconnectAttempts(n int) Option {
	return func(c *Client) {
		c.maxReconnectAttempts = n
	}
}

// WithHeartbeatInterval sets the interval between WebSocket ping frames.
func WithHeartbeatInterval(d time.Duration) Option {
	return func(c *Client) {
		c.heartbeatInterval = d
	}
}
