// Code generated by ws-codegen; DO NOT EDIT.

package realtime

// EventType constants for server-sent and client-sent message types.
const (
	EventSubscribed = "subscribed"
	EventItemNew = "item.new"
	EventItemEnriched = "item.enriched"
	EventClustersRanked = "clusters.ranked"
	EventStoryDevelopment = "story.development"
	EventStoryPriorityChanged = "story.priority_changed"
	EventClusterEvent = "cluster.event"
	EventError = "error"
	EventSubscribe = "subscribe"
)

// SubscribeFilters — Filters to control which events are delivered
type SubscribeFilters struct {
	Categories []string `json:"categories,omitempty"` // Filter by news categories (e.g., "politics", "technology"). Empty = all.
	Sources []string `json:"sources,omitempty"` // Filter by source IDs. Empty = all.
	Keywords []string `json:"keywords,omitempty"` // Filter by keywords in article titles (case-insensitive, OR logic).
	Keyword *string `json:"keyword,omitempty"` // Single keyword filter (legacy, prefer `keywords` array). Deprecated.
	Topics []string `json:"topics,omitempty"` // Event topics to subscribe to. Empty = all topics.
	Entities []int64 `json:"entities,omitempty"` // Filter by entity IDs for enrichment events. Empty = no entity filter.
	IncludeEmbeddings *bool `json:"include_embeddings,omitempty"` // Include embedding vectors in events (Pro+ only).
	EmbeddingFilters []EmbeddingFilter `json:"embedding_filters,omitempty"` // Semantic similarity filters (Pro+ only, max 10).
}

// EmbeddingFilter — A semantic similarity filter using a pre-computed embedding vector
type EmbeddingFilter struct {
	Embedding []float32 `json:"embedding"` // 1536-dimensional embedding vector (text-embedding-3-small compatible)
	Threshold *float32 `json:"threshold,omitempty"` // Minimum cosine similarity threshold (0.5-1.0)
	Label *string `json:"label,omitempty"` // Optional user-defined label for this filter
}

// Item — A news article
type Item struct {
	Id int64 `json:"id"`
	UrlHash string `json:"url_hash"` // SHA-256 hex hash of the article URL
	Slug *string `json:"slug,omitempty"` // SEO-friendly URL slug
	Title string `json:"title"`
	Url string `json:"url"`
	SourceId string `json:"source_id"`
	SourceName string `json:"source_name"`
	Category string `json:"category"`
	SourceLanguage *string `json:"source_language,omitempty"`
	PublishedAt *int64 `json:"published_at,omitempty"` // Unix milliseconds (0 if unknown)
	DiscoveredAt int64 `json:"discovered_at"` // Unix milliseconds
	Excerpt *string `json:"excerpt,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	PlaceholderImageUrl *string `json:"placeholder_image_url,omitempty"`
	VideoUrl *string `json:"video_url,omitempty"`
	ContentStatus *string `json:"content_status,omitempty"`
	HeadlineSummary *string `json:"headline_summary,omitempty"`
}

// StoryDevelopmentData — Data about a new development in an ongoing story
type StoryDevelopmentData struct {
	ClusterId int64 `json:"cluster_id"`
	Title string `json:"title"`
	Description string `json:"description"`
	Significance string `json:"significance"` // Significance level of the development
	Headline *string `json:"headline,omitempty"` // Current story headline
	Category *string `json:"category,omitempty"`
	PreviousHeadline *string `json:"previous_headline,omitempty"`
	NewHeadline *string `json:"new_headline,omitempty"`
	CreatedAtMs *int64 `json:"created_at_ms,omitempty"` // Unix milliseconds
	EnrichmentSeq *int `json:"enrichment_seq,omitempty"` // Sequential enrichment counter
}

// StoryPriorityChangedData — Data about a story's priority level changing
type StoryPriorityChangedData struct {
	ClusterId int64 `json:"cluster_id"`
	Headline string `json:"headline"`
	Category string `json:"category"`
	PreviousPriority string `json:"previous_priority"`
	NewPriority string `json:"new_priority"`
	OverallScore *float64 `json:"overall_score,omitempty"`
	AccelerationScore *float64 `json:"acceleration_score,omitempty"`
}

// ClusterEventData — Cluster lifecycle event (create, merge, split, split_created)
type ClusterEventData struct {
	Action string `json:"action"`
	ClusterId int64 `json:"cluster_id"`
	Detail map[string]interface{} `json:"detail,omitempty"` // Action-specific details
}

type ErrorData struct {
	Error string `json:"error"` // Human-readable error message
}

// SubscribedEvent — Confirmation that subscription was accepted
type SubscribedEvent struct {
	Type string `json:"type"`
	EmbeddingFilters *int `json:"embedding_filters,omitempty"` // Number of active embedding filters (if any)
}

// ItemNewEvent — A new article matching your filters
type ItemNewEvent struct {
	Type string `json:"type"`
	Data Item `json:"data"` // A news article
	Embedding []float32 `json:"embedding,omitempty"` // Article embedding vector (only if include_embeddings is set)
	EmbeddingModel *string `json:"embedding_model,omitempty"` // Model used to generate the embedding
	Similarity *float32 `json:"similarity,omitempty"` // Cosine similarity score (only with embedding_filters)
}

// ItemEnrichedEvent — An article has been enriched with entity data
type ItemEnrichedEvent struct {
	Type string `json:"type"`
	Data Item `json:"data"` // A news article
	EntityIds []int64 `json:"entity_ids"` // Entity IDs linked to this article
}

// ClustersRankedEvent — Updated cluster/story rankings
type ClustersRankedEvent struct {
	Type string `json:"type"`
	Data []map[string]interface{} `json:"data"`
	Updated *bool `json:"updated,omitempty"` // Always true for ranking updates
}

// StoryDevelopmentEvent — A significant development in an ongoing story
type StoryDevelopmentEvent struct {
	Type string `json:"type"`
	Data StoryDevelopmentData `json:"data"` // Data about a new development in an ongoing story
}

// StoryPriorityChangedEvent — A story's priority level has changed
type StoryPriorityChangedEvent struct {
	Type string `json:"type"`
	Data StoryPriorityChangedData `json:"data"` // Data about a story's priority level changing
}

// ClusterEventEvent — Cluster lifecycle event (create, merge, split)
type ClusterEventEvent struct {
	Type string `json:"type"`
	Data ClusterEventData `json:"data"` // Cluster lifecycle event (create, merge, split, split_created)
}

// ErrorEvent — An error occurred processing your request
type ErrorEvent struct {
	Type string `json:"type"`
	Error string `json:"error"` // Human-readable error message
}

// rawEvent is used internally for initial type dispatch.
type rawEvent struct {
	Type string `json:"type"`
}
